@host = http://localhost:5225

### Attractions

GET {{host}}/api/attractions
POST {{host}}/api/attractions
PATCH {{host}}/api/attractions/{attractionId}/publish
PATCH {{host}}/api/attractions/{attractionId}/archive

### Rules

GET {{host}}/api/rules
POST {{host}}/api/rules

### Scenarios

POST {{host}}/api/attractions/{attractionId}/scenarios
PATCH {{host}}/api/attractions/{attractionId}/scenarios/{scenarioId}/publish
PATCH {{host}}/api/attractions/{attractionId}/scenarios/{scenarioId}/archive
