// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tripder.Infrastructure.Persistence;

#nullable disable

namespace Tripder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AttractionRuleDefinition", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RulesId")
                        .HasColumnType("uuid");

                    b.HasKey("AttractionId", "RulesId");

                    b.HasIndex("RulesId");

                    b.ToTable("AttractionRules", (string)null);
                });

            modelBuilder.Entity("AttractionTag", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("AttractionId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("AttractionTags", (string)null);
                });

            modelBuilder.Entity("RuleDefinitionScenario", b =>
                {
                    b.Property<Guid>("RulesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("RulesId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioRules", (string)null);
                });

            modelBuilder.Entity("ScenarioTag", b =>
                {
                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ScenarioId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ScenarioTags", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Attraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CatalogFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CatalogTo")
                        .HasColumnType("date");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Attractions", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.DayOfWeekEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RuleDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleDefinitionId");

                    b.ToTable("RuleDays", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.RuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Params")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("RuleDefinitions", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AttractionId");

                    b.ToTable("Scenarios", (string)null);
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AttractionRuleDefinition", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Attraction", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.RuleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttractionTag", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Attraction", null)
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RuleDefinitionScenario", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.RuleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Scenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScenarioTag", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Scenario", null)
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Attraction", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Tripder.Domain.AttractionDefinition.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("AttractionId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<string>("LocationName")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("LocationName");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.DayOfWeekEntry", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.RuleDefinition", null)
                        .WithMany("Days")
                        .HasForeignKey("RuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Image", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Scenario", null)
                        .WithMany("Images")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Scenario", b =>
                {
                    b.HasOne("Tripder.Domain.AttractionDefinition.Entities.Attraction", "Attraction")
                        .WithMany("Scenarios")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Attraction", b =>
                {
                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.RuleDefinition", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Tripder.Domain.AttractionDefinition.Entities.Scenario", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
